# dynamic_title = true
# enable_experimental_conpty_backend = true
# live_config_reload = true

[colors.bright]
black = "#4C566A"
blue = "#81A1C1"
cyan = "#8FBCBB"
green = "#A3BE8C"
magenta = "#B48EAD"
red = "#BF616A"
white = "#ECEFF4"
yellow = "#EBCB8B"

[colors.normal]
black = "#3B4252"
blue = "#81A1C1"
cyan = "#88C0D0"
green = "#A3BE8C"
magenta = "#B48EAD"
red = "#BF616A"
white = "#E5E9F0"
yellow = "#EBCB8B"

[colors.primary]
background = "#0A1F2F"
foreground = "#D8DEE9"

[cursor]
style = "Beam"
unfocused_hollow = true

[env]
# TERM = "xterm-256color"

[font]
size = 8

[font.bold]
family = "mononoki NF"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "mononoki NF"
style = "Italic"

[font.normal]
family = "mononoki NF"
style = "Regular"

[font.offset]
x = 0
y = 1

[scrolling]
# auto_scroll = true
history = 1000

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
decorations = "full"
dynamic_padding = false
opacity = 0.9

[window.dimensions]
columns = 85
lines = 28

[window.padding]
x = 0
y = 0
