#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap           7

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer false

# border
bspc config focused_border_color        "#41CCC4"
bspc config normal_border_color         "#7E57C2"
bspc config active_border_color         "#7E57C2"

# Rules
# bspc rule -a mpv state=fullscreen
bspc rule -a Zathura        state=tiled
bspc rule -a Pavucontrol    state=floating
bspc rule -a feh            state=floating
bspc rule -a zoom           state=floating

bspc config focus_follows_pointer true

# Configure the wallpaper
feh --bg-fill $HOME/Pictures/wallpapers/15.jpg

# Autostart
xsetroot -cursor_name left_ptr & 

picom -b &

pgrep -x sxhkd > /dev/null || sxhkd &

~/.config/polybar/launch.sh

pkill dunst
dunst -conf ~/.config/dunst/dunstrc &
