#! /bin/sh

# Helper for bspwm client
_bc () {
  bspc $@
}

pgrep -x sxhkd > /dev/null || sxhkd &

_bc monitor -d I II III IV V VI VII VIII IX X

_bc config border_width         0
_bc config window_gap           7
_bc config top_padding          26
# _bc config border_radius        10

_bc config split_ratio          0.52
_bc config borderless_monocle   true
_bc config gapless_monocle      true

# border
# _bc config focused_border_color        "#FFCC80"
# _bc config normal_border_color         "#7E57C2"

# Rules
# bspc rule -a mpv state=fullscreen
_bc rule -a Zathura        state=tiled
_bc rule -a Pavucontrol    state=floating
_bc rule -a feh            state=floating
_bc rule -a zoom           state=floating
_bc rule -a discord        state=floating

_bc config focus_follows_pointer true

# Configure the wallpaper
# feh --bg-fill $HOME/Pictures/wallpaper.jpg

# Autostart
xsetroot -cursor_name left_ptr & 

picom -b &

pgrep -x sxhkd > /dev/null || sxhkd &

~/.config/polybar/launch.sh

pkill dunst
dunst -conf ~/.config/dunst/dunstrc &

hsetroot -solid "#143F5E"
